numchannels: 20
audiogain: 1
fftN: 2048
fftlog: Y
vulog: Y
0: vu
1: vu
2: vu
3: vu
4: fft
5: fft
6: fft
7: fft
8: fft
9: fft
10: fft
11: fft
12: fft
13: fft
14: fft
15: fft
16: fft
17: fft
18: fft
19: fft