numchannels: 20
audiogain: 1
fftN: 2048
fftlog: N
vulog: Y
0: fft
1: fft
2: fft
3: fft
4: fft
5: fft
6: fft
7: fft
8: fft
9: fft
10: fft
11: fft
12: fft
13: fft
14: fft
15: fft
16: fft
17: fft
18: fft
19: fft